version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    ports:
      - "8966:8966"
    depends_on:
      - db
