version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
      - PORT=8966
      - TOKEN_PASSWORD=${TOKEN_PASSWORD}
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    ports:
      - "8966:8966"
    depends_on:
      - db
